---
name: Catalyst-Plugin-Cache-FastMmap
version: 0.5
author:
  - |-
    Christian Hansen, C<ch@ngmedia.com>
    Sebastian Riedel C<sri@oook.de>
abstract: Mmap cache
license: perl
requires:
  Cache::FastMmap: 0
provides:
  Catalyst::Plugin::Cache::FastMmap:
    file: lib/Catalyst/Plugin/Cache/FastMmap.pm
    version: 0.5
generated_by: Module::Build version 0.2609
